version: 1.0.{build}
configuration: Release
image: Visual Studio 2017 RC
before_build:
  - dotnet restore
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
environment:
  nuget_user: oguzhansoykan@outlook.com
  nuget_password:
    secure: w73Xs1Is7iK/DtAOf0XTHg==
  COVERALLS_REPO_TOKEN:  
    secure: BolGC6FG7Pv51emvIKeU8n5Fx4jUEFyX9
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
after_build:
 - cmd: nuget pack "src\Autofac.Extras.IocManager" -o "nupkg/" 
 - cmd: nuget pack "src\Autofac.Extras.IocManager.DynamicProxy" -o "nupkg/"
test:
  assemblies: 
    - test\Autofac.Extras.IocManager.Tests\bin\Debug\net452\win7-x64\Autofac.Extras.IocManager.Tests.dll
    - test\Autofac.Extras.IocManager.Tests\bin\Debug\net452\win7-x64\Autofac.Extras.IocManager.DynamicProxy.Tests.dll
after_test: 
  - tools\coverage\opencover\OpenCover.Console.exe -register:user -target:"tools\xunitrunner\xunit.console.x86.exe"   -targetargs:"test\Autofac.Extras.IocManager.Tests\bin\Debug\net452\win7-x64\Autofac.Extras.IocManager.Tests.dll test\Autofac.Extras.IocManager.DynamicProxy.Tests\bin\Debug\net452\win7-x64\Autofac.Extras.IocManager.DynamicProxy.Tests.dll -noshadow" -filter:"+[Autofac.Extras.IocManager*]* -[Autofac.Extras.IocManager.T*]* -[Autofac.Extras.IocManager.DynamicProxy.T*]*" -output:xunit_opencovertests.xml -coverbytest:*.Tests.dll
  - tools\coverage\coveralls.net\csmacnz.Coveralls.exe --opencover -i xunit_opencovertests.xml --repoToken %COVERALLS_REPO_TOKEN% --commitBranch %APPVEYOR_REPO_BRANCH%
deploy:
- provider: NuGet
  on:
    branch: master
  api_key:
    secure: liSTqN52OJQy9fZJk6gubSgYBAy4EXcEPCDSCLJ/3T9cZufzpTwvBlGPLX+iP2n9
artifacts:
- path: '**\.nupkg/'
