version: 1.0.{build}
before_build:
- cmd: dotnet.exe restore
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
environment:
  nuget_user: oguzhansoykan@outlook.com
  nuget_password:
    secure: w73Xs1Is7iK/DtAOf0XTHg==
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
after_build:
- cmd: dotnet pack "src\Autofac.Extras.IocManager" -c "Release" -o "nupkg/"
 
test:
  assemblies:
  - test\Autofac.Extras.IocManager\bin\Debug\net452\win7-x64\Autofac.Extras.IocManager.Tests.dll
deploy:
- provider: NuGet
  api_key:
    secure: liSTqN52OJQy9fZJk6gubSgYBAy4EXcEPCDSCLJ/3T9cZufzpTwvBlGPLX+iP2n9
artifacts:
- path: '**\.nupkg/'
